version: 2
jobs:
  build:
    docker:
      - image: spbk/circleci-golang
    working_directory: /go/src/github.com/sbstjn/go-lambda-example

    steps:
      - checkout

      - run: touch .env

      - run: make install
      - run: make test
      - run: make build
      - run: make package
      - run: make deploy
      - run: make describe
      - run: make describe | jq -r ".Stacks[0].Outputs[0].OutputValue" -j

      - store_artifacts:
          path: /go/src/github.com/sbstjn/go-lambda-example/dist
          destination: dist
      - store_artifacts:
          path: /go/src/github.com/sbstjn/go-lambda-example/package.yml
          destination: package.yml
      - store_artifacts:
          path: /go/src/github.com/sbstjn/go-lambda-example/endpoint.txt
          destination: endpoint.txt